-- Your SQL goes here

CREATE TABLE devices (
  id TEXT PRIMARY KEY NOT NULL,
  label CHARACTER(32) NOT NULL,
  power UNSIGNED SHORT INTEGER,
  hue UNSIGNED SHORT INTEGER,
  saturation UNSIGNED SHORT INTEGER,
  brightness UNSIGNED SHORT INTEGER,
  kelvin UNSIGNED SHORT INTEGER
)
